### PR TITLE
AMinerRemoteControl - Whitelisting

### LINKED ISSUE #106: AminerRemoteControl: Whitelist specific path
A scenario is that when running the AMiner in detection mode, one new anomaly occurs over and over, because something in the system has changed (e.g., ip). The operator confirms that this is a valid change and commands the AMiner to relearn this one specific value (add to persistency or override previous value).

### PR DESCRIPTION
**Pull request by dITySoftware**
Fixes #106

### CODE REVIEW

**Comment by dITySoftware** [comment]
should the NewMatchPathValueDetector also implement the whitelist_event method?

**Comment by dITySoftware** [comment]
fixes #106

**Comment by landauermax** [comment]
> 
> 
> should the NewMatchPathValueDetector also implement the whitelist_event method?

Yes. Or is there any reason why we should not support the method for that detector?

**Review by whotwagner — CHANGES_REQUESTED** [review]
Please rebase. We renamed the aminer

**Comment by dITySoftware** [comment]
The unittests are failing in the new code allowlist was already used instead of whitelist. Please accept PR #192 first.

**Review by landauermax — CHANGES_REQUESTED** [review]
Whitelist should be named allowlist

**Comment by dITySoftware** [comment]
> Whitelist should be named allowlist

fixed example in aminerRemoteControlDemo. All other conflicts need to be fixed after PR #192 is accepted. PR #192 refactors whitelist to allowlist.

**Review by landauermax — APPROVED** [review]
Sorry, wrong PR

**Review by landauermax — APPROVED** [review]
Looks good to me

**Comment by landauermax** [comment]
@whotwagner you still have changes requested that prevent this PR from being merged. Please review.

**Comment by dITySoftware** [comment]
> @whotwagner you still have changes requested that prevent this PR from being merged. Please review.

@landauermax can you merge it without the approval? We discussed this with @whotwagner.

**Comment by landauermax** [comment]
Unfortunately github blocks merging as long as there are changes requested. I will ask @whotwagner to accept the changes as soon as possible.

**Review by whotwagner — APPROVED** [review]

**Comment by dITySoftware** [comment]
Please accept PR #305 first.

**Pull request merged**
