### PR TITLE
Getting started test

### LINKED ISSUE #308: Create script that executes GettingStarted and TryItOut of AMiner Wiki automatically as own travis job

### PR DESCRIPTION
**Pull request by dITySoftware**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #123'-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #308 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

# Describe changes:
- adds a Travis test for the Getting Started and Try It Out demos.
-
-

### CODE REVIEW

**Review by whotwagner — CHANGES_REQUESTED** [review]
Currently the tests use static configurations and assume that we do not change anything in the Wiki. We could not rely on that therefore we should download all the configurations from the website in order to be in sync with our tests.

**Comment by dITySoftware** [comment]
> Currently the tests use static configurations and assume that we do not change anything in the Wiki. We could not rely on that therefore we should download all the configurations from the website in order to be in sync with our tests.

How? These are only available in the rendered MD file.

**Comment by dITySoftware** [comment]
> Currently the tests use static configurations and assume that we do not change anything in the Wiki. We could not rely on that therefore we should download all the configurations from the website in order to be in sync with our tests.

This is very problematic as the wiki is based on the master branch and would fail Travis if for example parameters are changed etc.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Comment by landauermax** [comment]
@whotwagner you still have changes requested. Problems were solved as described in issue 308. Is this solution fine with you?

**Comment by whotwagner** [comment]
We don't need this checks regularily. We need it when we release a new version of logdata-anomaly-miner. And then it is crucial for us that the config is taken from the the wiki. We need a script for that in order to know what we have to change in the wiki.

If we statically create a config that appears to be the config at the wiki, we would never know  if the wiki works for sure. Maybe someone changed the config in the wiki or the config in this test and those configs are not in sync anymore.

**Comment by dITySoftware** [comment]
> We don't need this checks regularily. We need it when we release a new version of logdata-anomaly-miner. And then it is crucial for us that the config is taken from the the wiki. We need a script for that in order to know what we have to change in the wiki.
> 
> If we statically create a config that appears to be the config at the wiki, we would never know if the wiki works for sure. Maybe someone changed the config in the wiki or the config in this test and those configs are not in sync anymore.

I think they should be executed every time. As in the other case changes, which destroy the config, would not be seen immediately.

Maybe there should be a rule that nobody is allowed to changed the configs in the wiki without opening a new issue or something like that.

However I think it is not necessary to run coverage tests every time. They take about 10 minutes every time - 100 credits per run..
Please discuss that in issue #326.

**Comment by whotwagner** [comment]
> > We don't need this checks regularily. We need it when we release a new version of logdata-anomaly-miner. And then it is crucial for us that the config is taken from the the wiki. We need a script for that in order to know what we have to change in the wiki.
> > If we statically create a config that appears to be the config at the wiki, we would never know if the wiki works for sure. Maybe someone changed the config in the wiki or the config in this test and those configs are not in sync anymore.
> 
> I think they should be executed every time. As in the other case changes, which destroy the config, would not be seen immediately.
> 
> Maybe there should be a rule that nobody is allowed to changed the configs in the wiki without opening a new issue or something like that.
> 
> However I think it is not necessary to run coverage tests every time. They take about 10 minutes every time - 100 credits per run..
> Please discuss that in issue #326.

OK, then please use a command-line-argument for the testscript where we can set the branch of the wiki. And extract the configs from the code-sections of the markdown-files.

**Pull request merged**
