### PR TITLE
Fixed a bug in update_var_type

### PR DESCRIPTION
**Pull request by hoeldg**

### CODE REVIEW

**Review by dITySoftware — CHANGES_REQUESTED** [review]
This actually is no bug. There is no need to use elif over if, when every if contains a return. In this case there is no way more than one if is called.

**Comment by dITySoftware** [comment]
Please remove the redundant return statements or close the PR.

**Comment by hoeldg** [comment]
I have changed the elifs back to ifs and added returns

**Comment by dITySoftware** [comment]
he fixed code is in PR #188.

**Pull request closed without merging**
