### PR TITLE
Persistence backup

### LINKED ISSUE #200: Create backups of persistency
There should be a parameter for the command line that backups the persistency in regular intervals. Also, there should be a command for the remote control that saves the persistency when executed.

The persistency should be copied into a directory /var/lib/aminer/backup/yyyy-mm-dd-hh-mm-ss/...

There should also be the possibility to restore configs, by remote control, config settings, etc.

### PR DESCRIPTION
**Pull request by dITySoftware**
Fixes #200

### CODE REVIEW

**Review by whotwagner — CHANGES_REQUESTED** [review]
We need Command-Line parameters for --backup and --restore.

**Comment by dITySoftware** [comment]
> We need Command-Line parameters for --backup and --restore.

I understand the --restore parameter, but what should happen when the AMiner is started with --backup?
Also if the user is able to determine which backup he needs, he will also be able to just copy the folder into the main persistence folder..

example usage could be
`aminer --Config /tmp/config.py --restore 2020-10-29-10-00-00`
Here the user would be allowed only to restore persistence from the current persistence dir.

another example could be
`aminer --Config /tmp/config.py --restore /tmp/lib/aminer/backup/2020-10-29-10-00-00`
Here the user could use any directory.

**Comment by landauermax** [comment]
I would suggest to only have a --restore parameter. Creating backups is done with the remote interface as implemented.

Also, for the remote control, it would be good to have a command list-backups that returns all available backup directories that can be used for restoring.

**Comment by dITySoftware** [comment]
> I would suggest to only have a --restore parameter. Creating backups is done with the remote interface as implemented.
> 
> Also, for the remote control, it would be good to have a command list-backups that returns all available backup directories that can be used for restoring.

i will add the first option as it will be same like the --Remove Parameter.

**Comment by whotwagner** [comment]
We decided to create a new tool for that task

**Comment by dITySoftware** [comment]
> We decided to create a new tool for that task

I have already added the functionality. Can it stay in the main aminer program? I will also add the new tool.

**Review by whotwagner — APPROVED** [review]

**Pull request merged**
