### PR TITLE
VTD CM test

### LINKED ISSUE #565: Add the CM-test to the VCD

### PR DESCRIPTION
**Pull request by hoeldg**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #123'-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #565 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

# Describe changes:
-  Added the CM test in the VTD, added unit-tests for it and fixed some bugs in the unit tests

### CODE REVIEW

**Comment by dITySoftware** [comment]
Please fix the deepsource issues by using enumerate. The readability gain outstands the performance loss of this call.

Also i guess you have renamed the data files and forgot add the files. Please run following command before commiting:
git add ./aecid-testsuite/unit/data/*

**Comment by hoeldg** [comment]
The Problem has not already been resolved, because of lines like 354 in the VCDTest.
There deepsorce sugests to use enumerate(...) instead of range(len(...)), even though, the additional argument is not used in the loop.
As for the data files. It was not renamed but deleted because the test in the VTD-Test was rewritten for easier readability. But because the same file is also used in the ETD-Tests, I add it in the next commit

**Comment by dITySoftware** [comment]
> The Problem has not already been resolved, because of lines like 354 in the VCDTest.
> There deepsorce sugests to use enumerate(...) instead of range(len(...)), even though, the additional argument is not used in the loop.
> As for the data files. It was not renamed but deleted because the test in the VTD-Test was rewritten for easier readability. But because the same file is also used in the ETD-Tests, I add it in the next commit

Ok, in that case please add following in the same line of the reported issue (note the two spaces before the #
  # skipcq: PTC-W0060

Also please rename the AnalysisNormalisationSchema and AnalysisValidationSchema to .json to resolve the conflict.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Review by landauermax — APPROVED** [review]
Looks good to me

**Review by landauermax — APPROVED** [review]
Looks good to me

**Pull request merged**
