### PR TITLE
214 xml log parser

### LINKED ISSUE #1222: XML log parser
Some log files are available in XML format, such as Windows Security Logs. It would be good to have an input model that is able to process XML logs, in the same way that the JSON state machine is able to parse JSON logs.

### PR DESCRIPTION
**Pull request by ernstleierzopf**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1222 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by landauermax** [comment]
Thanks, looks good. But please also add the XmlModelElement to the aeciddocs.

**Comment by landauermax** [comment]
Just to make sure, I was referring to this documentation: https://github.com/ait-aecid/logdata-anomaly-miner/blob/development/docs/CONFIGURATION.rst

**Comment by ernstleierzopf** [comment]
> Just to make sure, I was referring to this documentation: https://github.com/ait-aecid/logdata-anomaly-miner/blob/development/docs/CONFIGURATION.rst

Done now.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Pull request merged**
