### PR TITLE
added stop_learning_time and stop_learning_no_anomaly_time

### LINKED ISSUE #831: Parameters for analysis components to switch to detection mode
Changing the learn_mode of the aminer requires a restart or waiting until a certain amount of time has passed, which is not convenient. There was therefore a request to be able to set in the config after how much time the learn_mode should be automatically changed from True to False. E.g., switch_learn_mode_false_time = 3600 will cause that the detector changes its learn_mode automatically after 3600 seconds (based on log data timestamps).

In addition, it should also be possible to change the learn_mode after no anomalies were reported for a certain amount of time. E.g., switch_learn_mode_false_anomaly_time = 3600 means that when no anomalies are produced by this detector for 3600 seconds, the learn mode changes.

### PR DESCRIPTION
**Pull request by dITySoftware**
…rsetDetector.

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [ ] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [ ] Issues exist for this PR
- [ ] I added related issues using the "Fixes #<issue-id>"-notations
- [ ] This Pull-Requests merges into the "development"-branch

Fixes #831 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by dITySoftware** [comment]
@landauermax could you please review the implementation for the first class, before I implement the parameters for the other classes?

**Comment by landauermax** [comment]
I think it looks good, but I would use learn_mode rather than auto_include_flag in the logging messages because most people using the yaml config are most likely not aware of the variable auto_include_flag.

**Comment by dITySoftware** [comment]
> I think it looks good, but I would use learn_mode rather than auto_include_flag in the logging messages because most people using the yaml config are most likely not aware of the variable auto_include_flag.

Thanks, I will change that.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Pull request merged**
