### PR TITLE
Implemented mechanism to allow granular configuration of LogResources.

### LINKED ISSUE #1155: Add possibility to run some LogResources as json input and some as normal text input.
```
LogResourceList:

   - url: "file:///var/log/apache2/access.log"
   - url: "unix:///var/lib/akafka/aminer.sock"
     type: json  # Konfiguriert den ByteStream
     parser_id: kafka_audit_logs  # Konfiguriert den zugehörigen Parser


Parser:
   - id: kafka_audit_logs
     type: AuditDingsParser

   - id: ApacheAccessModel
     start: true
```

### PR DESCRIPTION
**Pull request by ernstleierzopf**
No breaking changes were introduced. The old configurations still work the same.

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1155

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by ernstleierzopf** [comment]
PR is ready for review.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Comment by landauermax** [comment]
Please also update the documentation for the new functions, specifically this part: https://aeciddocs.ait.ac.at/logdata-anomaly-miner/development/CONFIGURATION.html#logresourcelist

**Comment by ernstleierzopf** [comment]
> Please also update the documentation for the new functions, specifically this part: https://aeciddocs.ait.ac.at/logdata-anomaly-miner/development/CONFIGURATION.html#logresourcelist

done.

**Pull request merged**
