### PR TITLE
fixed overwriting docker-images on paralell builds

### PR DESCRIPTION
**Pull request by whotwagner**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [ ] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [ ] Issues exist for this PR
- [ ] I added related issues using the "Fixes #123'-notations
- [ ] This Pull-Requests merges into the "development"-branch

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-
-
-

### CODE REVIEW

**Comment by dITySoftware** [comment]
why are all aminer configs recreated in the new aminercfg directory? Should they be moved there or are they on purpose re-created?

**Comment by dITySoftware** [comment]
probably these files were not added into the commit as add was not run with -f.

**Review by 4cti0nfi9ure — APPROVED** [review]
looks good

**Comment by dITySoftware** [comment]
> looks good

I think these config files should not be twice in the project.

**Pull request closed without merging**
