### PR TITLE
Fix feature list order in PCA detector

### LINKED ISSUE #1291: PCA detector feature list order
When values are optional or missing, the order of the feature list in the PCA detector changes incorrectly.

### PR DESCRIPTION
**Pull request by landauermax**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [X] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [X] Issues exist for this PR
- [X] I added related issues using the "Fixes #<issue-id>"-notations
- [X] This Pull-Requests merges into the "development"-branch

Fixes #1291

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

# Describe changes:
- Fix feature list in PCA detector

### CODE REVIEW

**Comment by ernstleierzopf** [comment]
restarted DeepSource analysis..

**Comment by ernstleierzopf** [comment]
somehow Deepsource does not work here. @landauermax could you please push an empty commit or do something to get Deepsource running?

**Comment by ernstleierzopf** [comment]
@landauermax please sync your repository to the current commit of the development branch to fix CI.

**Comment by landauermax** [comment]
@ernstleierzopf I merged the development branch but the test still fail.

**Comment by ernstleierzopf** [comment]
please accept the fix in #1308 and sync the fork.

**Comment by landauermax** [comment]
I did, but the tests still fail.

**Comment by ernstleierzopf** [comment]
can't fix. Please create a new branch from your up to date development branch, copy all of the changes and create a new pull request with that.
The changed code has nothing to do with the failed tests and the new fix worked just fine yesterday..

**Review by whotwagner — APPROVED** [review]

**Pull request closed without merging**
