### PR TITLE
added a pr-template

### LINKED ISSUE #215: Create a pull-request-template

### PR DESCRIPTION
**Pull request by whotwagner**
This PR introduces a PR-Template with checkboxes to make it easier to review

Fixes #215

### CODE REVIEW

**Review by dITySoftware — APPROVED** [review]
How does this Template work? Does the PR writer have an interface where he can check these boxes?

**Comment by dITySoftware** [comment]
Please note that Fixes #xxx works only if the submitter has enough permissions to actually close the issue.

**Comment by whotwagner** [comment]
> How does this Template work? Does the PR writer have an interface where he can check these boxes?

When you create a PR you will see this template

**Comment by whotwagner** [comment]
> Please note that Fixes #xxx works only if the submitter has enough permissions to actually close the issue.

No, Fixes #xxx works even if the submittes does not have any permissions. But the issues will NOT be fixed it the PR was merged into the development branch. They will be fixed after we create a new release and merge from development into the main(master) branch

**Review by landauermax — APPROVED** [review]
Looks good to me

**Pull request merged**
