### PR TITLE
Fix yaml issues

### PR DESCRIPTION
**Pull request by dITySoftware**

### CODE REVIEW

**Review by landauermax — APPROVED** [review]
Looks good to me

**Comment by dITySoftware** [comment]
Fixes #171

**Comment by dITySoftware** [comment]
Fixes #170

**Comment by dITySoftware** [comment]
Fixes #169

**Comment by dITySoftware** [comment]
Fixes #168

**Comment by dITySoftware** [comment]
Fixes #167

**Comment by dITySoftware** [comment]
Fixes #166

**Comment by dITySoftware** [comment]
Fixes #164

**Comment by dITySoftware** [comment]
Fixes #163

**Comment by dITySoftware** [comment]
Fixes #162

**Comment by dITySoftware** [comment]
Fixes #161

**Comment by dITySoftware** [comment]
Fixes #107

**Pull request merged**
