### PR TITLE
added nullable functionality to JsonModelElements.

### LINKED ISSUE #1061: JsonParser: Enhance parser tree format with optional null value
Currently the log lines:
```
{„a“: null}
{„a“: {„b“: „b“}}
```

can be parser with the parser:
```
          - id: b
            type: FixedDataModelElement
            name: 'b'
            args: 'b'

          - id: n
            type: FixedDataModelElement
            name: 'n'
            args: 'null'

          - id: json
            type: JsonModelElement
            name: 'model'
            optional_key_prefix: '_'
            key_parser_dict:
              a:
                b: b

          - id: json2
            type: JsonModelElement
            name: 'model2'
            optional_key_prefix: '_'
            key_parser_dict:
              a: n

          - id: first
            start: True
            type: FirstMatchModelElement
            name: 'first'
            args:
              - json2
              - json
```

which is hard to read and could be enhanced.

### LINKED ISSUE #1074: JsonParser: Bug related to optional elements that contain arrays
Following log line:
```
{"a": ["gh"]}
```
with following parser:
```
Parser:
        - id: a_str
          type: FixedDataModelElement
          name: 'a_str'
          args: 'hg'

        - id: json_1
          start: True
          type: JsonModelElement
          name: 'json_1'
          optional_key_prefix: '+'
          key_parser_dict:
            +a:
              - a_str
```
results in following error:
```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 480, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 89, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 336, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 156, in consume_data
    match_element = self.parsing_model.get_match_element('', match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 178, in get_match_element
    matches += self.parse_json_dict(self.key_parser_dict, json_match_data, current_path, match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 240, in parse_json_dict
    res = self.parse_json_array(json_dict, json_match_data, key, split_key, current_path, matches, match_context, i)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py", line 403, in parse_json_array
    if matches[-1] is None:
IndexError: list index out of range
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 590703 terminated unexpectedly with signal 0x100
```
The error does not occur if eighter "a" is not optional, nor if "gh" is not contained in an array

### PR DESCRIPTION
**Pull request by dITySoftware**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1061 
Fixes #1074 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by hoeldg** [comment]
Please fix the following bug:
The error
```
line 272, in parse_json_dict: if match_context.match_data[index + 4] == b'"':
BytesWarning: Comparison between bytes and int
aminer: Analysis child process 20334 terminated unexpectedly with signal 0x100
```
occurs, when trying to parse the line
```
{"a": null}
```
with the parser
```
Parser:
        - id: b_var0
          type: VariableByteDataModelElement
          name: 'b_var0'
          args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:"/@'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          nullable_key_prefix: '+'
          key_parser_dict:
            +a:
              b: b_var0
```

**Comment by whotwagner** [comment]
Please include tests with data: anull and nulla

**Comment by dITySoftware** [comment]
> Please fix the following bug: The error
> 
> ```
> line 272, in parse_json_dict: if match_context.match_data[index + 4] == b'"':
> BytesWarning: Comparison between bytes and int
> aminer: Analysis child process 20334 terminated unexpectedly with signal 0x100
> ```
> 
> occurs, when trying to parse the line
> 
> ```
> {"a": null}
> ```
> 
> with the parser
> 
> ```
> Parser:
>         - id: b_var0
>           type: VariableByteDataModelElement
>           name: 'b_var0'
>           args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:"/@'
> 
>         - id: json
>           start: True
>           type: JsonModelElement
>           name: 'model'
>           optional_key_prefix: '_'
>           nullable_key_prefix: '+'
>           key_parser_dict:
>             +a:
>               b: b_var0
> ```

Thanks for showing up this error. I have actually implemented a test for this case. However python3 does automatic type conversion in unittests, but not in the aminer. I have not known about that.
Running python with the -bb parameter raises the error as expected. https://www.commandlinux.com/man-page/man1/python3.1.html

**Comment by dITySoftware** [comment]
> Please include tests with data: anull and nulla

The null key case lead to an error. I have fixed it by changing the start of the find() function to the length of the split_key.

**Comment by hoeldg** [comment]
Please fix following behaviour:
The line
```
{}
```
can be parsed with the parser
```
Parser:
        - id: b_var0
          type: VariableByteDataModelElement
          name: 'b_var0'
          args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:"/@'

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          nullable_key_prefix: '+'
          key_parser_dict:
            _+a:
              b: b_var0
```
but not with the same parser where the prefixes are switched (```_+a:``` is replaced with ```+_a:```).

**Comment by dITySoftware** [comment]
> Please fix following behaviour: The line
> 
> ```
> {}
> ```
> 
> can be parsed with the parser
> 
> ```
> Parser:
>         - id: b_var0
>           type: VariableByteDataModelElement
>           name: 'b_var0'
>           args: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:"/@'
> 
>         - id: json
>           start: True
>           type: JsonModelElement
>           name: 'model'
>           optional_key_prefix: '_'
>           nullable_key_prefix: '+'
>           key_parser_dict:
>             _+a:
>               b: b_var0
> ```
> 
> but not with the same parser where the prefixes are switched (`_+a:` is replaced by `+_a:`).

Thanks for showing it up. It should work now. I have also added a test case for this.

**Comment by hoeldg** [comment]
The line ```{"a": {"b": null}}``` is successively parsed with the above parser (```+_a```) but shouldn't because ```b``` is not nullable

**Comment by hoeldg** [comment]
An error occurs when the line ```{"a": "b"}``` is parsed with the above parser (```+_a```)

**Comment by dITySoftware** [comment]
> An error occurs when the line `{"a": "b"}` is parsed with the above parser (`+_a`)

This bug is also fixed now.

**Comment by hoeldg** [comment]
Looks good to me

**Review by hoeldg — APPROVED** [review]

**Pull request merged**
