### PR TITLE
create different versions of the SyslogParsingModel for AIT-LDS versi…

### LINKED ISSUE #1260: SyslogParsingModel for AIT-LDSv2
Currently the SyslogParsingModel of the AIT-LDSv1 needs to be used to parse the logs from the AIT-LDSv2; however, this parser contains the element `DateTimeModelElement("time", b"%b %d %H:%M:%S", start_year=2020)`. The problem is that the AIT-LDSv2 requires a `start_year=2022`, otherwise the timestamps of parsed logs are processed in incorrect order when also other files with correct timestamps are used. We therefore need to replicate the SyslogParsingModel also to the ait-ldsv2 directory and change the start_year. If this is not desired, we need to find a way to set this parameter in another way through the configuration.

### PR DESCRIPTION
**Pull request by ernstleierzopf**
…ons 1 and 2.

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1260

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by landauermax** [comment]
I think the name of the file breaks our convention that the name of the parser as used in code is the same as the file name. Would it be okay to name all parser files SyslogParsingModel.py in /generic, /ait-lds, and /ait-lds2 and not have the AIT-LDSv1/2 in the file name?

**Comment by ernstleierzopf** [comment]
sure, I will change that.

**Comment by ernstleierzopf** [comment]
> I think the name of the file breaks our convention that the name of the parser as used in code is the same as the file name. Would it be okay to name all parser files SyslogParsingModel.py in /generic, /ait-lds, and /ait-lds2 and not have the AIT-LDSv1/2 in the file name?

Unfortunately it is not possible to have the same filename for three similar parsers in generic, ait-lds1 and ait-lds2. The reason for this is that during the setup all of the classes are copied into /etc/aminer/conf-enabled. If we rename the files, we will only have the last copied file available.
However I do not think it is that much of a problem. Here is an example usage of the parser:

```
  - id: SyslogParsingModel
    type: SyslogParsingModelAIT-LDSv2
    name: 'SyslogParsingModel'

  - id: model
    start: True
    type: FirstMatchModelElement
    name: 'model'
    args:
      - ApacheAccessParsingModel
      - ApacheErrorParsingModel
      - AuditdParsingModel
      - DnsParsingModel
      - EximParsingModel
      - SyslogParsingModel
      - SuricataFastParsingModel
      - SuricataEventParsingModel
      - OpenVpnParsingModel
```

**Comment by landauermax** [comment]
During which setup are these classes copied into /etc/aminer/conf-enabled? The aminer_install script should not do that - is there another setup script where this is the case?

**Comment by ernstleierzopf** [comment]
> During which setup are these classes copied into /etc/aminer/conf-enabled? The aminer_install script should not do that - is there another setup script where this is the case?

all of the dockerfiles copy the conf-available files into a flat structure in /etc/conf-enabled.
I am not sure if it would work to create a hierarchical copy, but even then it would be problematic, because the ConfigValidator in extension to the YamlConfig can not know which one of the configs we actually mean, when reading the yaml configuration.
If we define a SyslogParsingModel, which one do we mean - the generic, AIT-LDSv1 or AIT-LDSv2? That would not even be distinctable for humans without the context of the config - therefore I also can not program it.

The other solution would be to copy all of the code into every class and always copy the specific config you want to use in /etc/aminer/conf-enabled. I would not suggest this solution, because nobody wants to mess with the pre-defined parsers in the conf-enabled directory. You simply want to copy all of the existing parsers there during installation and use them as needed.

**Comment by landauermax** [comment]
I just talked with @whotwagner about this issue. It was not intended that the docker files copy all of the parsers into conf-enabled; only the ones in the conf-available/generic should be copied. This should resolve the problem. In case that the tests rely on the docker files and need other parsers than the generic ones, it should be possible to create/overwrite the parsers when starting the containers. Is this feasible?

**Comment by ernstleierzopf** [comment]
It is feasible, but I would have to duplicate the code for every SyslogParsingModel where only the start_year parameter of one DateTimeModelElement would be different, because the import would not be possible.

I can remove the ait-lds parsers in the Dockerfile. In aecid-testsuite/Dockerfile I need them for testing. However, I could work around that by copying the SyslogParsingModel as needed - this is not the issue.

Still not a fan of the proposed solution.. this might lead to headaches if someone simply copies all of the parsers and wonders why the dataset is not working with the existing configs.

Also to further on comment on the naming convention which lead to this discussion: there is no SyslogParsingModel class in any of the code, only the get_model method. So naming the file SyslogParsingModelAIT-LDSv2 is probably as good as naming it SyslogParsingModel. In the yaml config you only need to define the type with the specific parser - you can name it as you wish.

But I can implement it, if the team decides it is the better solution.

**Review by landauermax — APPROVED** [review]
Looks good to me

**Pull request merged**
