### PR TITLE
Add log line number to AMiner output.

### LINKED ISSUE #1334: Extend AMiner output for JsonConverterHandler
The project https://github.com/ait-aecid/aminer-configuration-engine requires the AMiner to have an unique identification for each log line in the .json output file. A line number for each log line the AMiner writes into the .json output file should therefore be implemented.

### PR DESCRIPTION
**Pull request by viktorbeck98**
# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1334 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

### CODE REVIEW

**Comment by ernstleierzopf** [comment]
not sure if this is the best solution for the issue. Do you want to have one unique identifier for each json object or for each log atom? I think there might be multiple outputs for each log atom.
If you want to have one identifier for each log line, this might work.

**Comment by ernstleierzopf** [comment]
Also the unittests and other tests must be adapted for the new output. Can help with that if needed :)

**Comment by landauermax** [comment]
I would really suggest to introduce a parameter in the aminer config that allows to switch the line number on and off, because i guess that in some cases (application of the aminer in live data, that has no "beginning" and a line number does not make sense) this information is not desired and will even be confusing.

**Comment by viktorbeck98** [comment]
Yes, it should be an identifier for each log line. Best is probably to add a parameter in the aminer config. Thereby, no tests have to be rewritten (if I'm not wrong) because the AMiner output will stay the same for the tests. I'll let you know if I need help (or the failed tests will tell) :)

**Pull request closed without merging**
