### PR TITLE
Feature rename aminer

### PR DESCRIPTION
**Pull request by whotwagner**

### CODE REVIEW

**Review by dITySoftware — COMMENTED** [review]
I don't think aminerRemoteControl.py should be deleted.
Please make sure you add the file to the commit by using
git add -f source/root/usr/lib/logdata-anomaly-miner/aminerremotecontrol.py

**Review by 4cti0nfi9ure — APPROVED** [review]
looks good

**Review by dITySoftware — COMMENTED** [review]
what happens when no python version is added in Travis?

**Comment by whotwagner** [comment]
> what happens when no python version is added in Travis?

the current default will be used. which is 3.6 at the moment

**Pull request merged**
